name: macOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-and-bench:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run Tests
        run: go test ./... -v

      - name: Run Benchmarks
        run: go test ./tests -bench=. -benchmem -timeout=10m
